name: NuGet Release Automation

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for tags

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' # Or the highest version you want to ensure is present

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests (Optional)
        run: dotnet test --configuration Release --no-build
        continue-on-error: true

      - name: Pack NuGet package
        run: dotnet pack --configuration Release -o . /p:Version="$(git describe --tags --abbrev=0)"

      - name: Push NuGet package to NuGet.org
        if: startsWith(github.ref, 'refs/heads/master')
        run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
        working-directory: .
